### PR TITLE
October Releases

### PR DESCRIPTION
**Pull request by N6REJ**

### CODE REVIEW

**Comment by jwaisner** [comment]
@N6REJ , looks like 21.2 didnt build right. I also moved the files for it into the October release as there was no need to separate the releases.

image

**Comment by N6REJ** [comment]
thats odd cause I'm running 21.2 here

**Comment by jwaisner** [comment]
Hmm, just checked using the separate pre-release thinking I botched something when merging them but still get the same error.

**Comment by N6REJ** [comment]
I'll try again this week... hopefully

**Comment by jwaisner** [comment]
Replaced by #15

**Pull request closed without merging**
